Downlad the class material at https://github.com/ramin-karimian/pythonClass

# 1. Introduction To Data Science

<img src="images/1.png" >


<img src="images/2.png" >

<img src="images/3.png" >

<img src="images/4.png" >

<img src="images/4.png" >

<img src="images/5.png" >

Numpy and Pandas both are common among data scientists

# 2. Numpy Package




* multidimentional arrays and matrices
* mathematical functions that base python lacks 


 #### Installation :
   run "**pip install numpy**" in Command Line Or Terminal

In [1]:
import numpy as np

## 2.1 Numpy Array Methods

np.array()

np.append()

np.shape()

np.insert()

np.delete()

np.mean()

np.median()

np.max()

np.min()

np.sum()

np.exp()

np.sqrt()

np.multiply(q,b) => a*b

np.dot(a,b)

np.cumsum()

np.std()

np.log()


...


In [8]:
my_list=[1,2,3,4,5]
my_array=np.array(my_list)

my_array=np.append(my_array,34)
print("append: ",my_array)
print("shape: ",np.shape(my_array))



append:  [ 1  2  3  4  5 34]
shape:  (6,)


In [10]:
#np.insert
my_array=np.insert(my_array,3,67)
print("insert :",my_array)
np.shape(my_array)

insert : [ 1  2  3 67 67  4  5 34]


(8,)

In [11]:
#np.delete
my_array=np.delete(my_array,[3,1])
print("delete: ",my_array)


delete:  [ 1  3 67  4  5 34]


In [12]:
#np.mean
print("mean: ",np.mean(my_array))

mean:  19.0


In [13]:
#np.median
print("median: ",np.median(my_array))


median:  4.5


In [14]:
#np.std()
print("std: ",np.std(my_array))


std:  24.255583549635194


## 2.2 Numpy Array Indexing

In [15]:
my_list=[1,2,3,4,5]
my_array=np.array(my_list)
print(my_array[0])


1


In [18]:
my_array[[1,4,2]]



array([2, 5, 3])

In [19]:
my_array[1:3]

array([2, 3])

In [22]:
my_array[1:]

array([2, 3, 4, 5])

In [27]:
my_array[::3]

array([1, 4])

In [28]:
my_array[::-1]

array([5, 4, 3, 2, 1])

In [29]:
my_array[my_array>2]

array([3, 4, 5])

## 2.3 Multidimentional array:

In [30]:
arr1=np.array([[1,2,3],[1,2,34]])

In [31]:
arr2=np.ndarray((2,3))
arr2


array([[ 324.,  256., 2304.],
       [ 225.,  196.,  225.]])

In [32]:
arr3=np.zeros((3,4))
arr3


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
arr4=np.ones((5,6))
arr4

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [35]:
arr6=np.random.randn(2,5)
arr6


array([[-2.12797949, -0.07558362, -0.11393567,  0.05300205, -0.63049821],
       [ 1.45164491,  0.11590113, -0.29081353,  0.32766355,  1.63734466]])

In [37]:
arr7=np.arange(4,10,2)
arr7

array([4, 6, 8])

In [38]:
arr5=np.eye(3)
arr5


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
#shape
arr6.shape[0]
arr6.shape[1]

5

## 2.4 Indexing Multidimentional Arrays


In [41]:
arr1

array([[ 1,  2,  3],
       [ 1,  2, 34]])

In [42]:
print("arr1[1,2]: ",arr1[1,2])


arr1[1,2]:  34


In [47]:
print(arr1[:,[0,1]])


[[1 2]
 [1 2]]


** Question 1**: 

create a 2-dimentional random array in shape (4,5) and reverse the items in the second elemnt in the first axis(dimention) which are inside the 3rd and 4th items in the second axis.


In [105]:
np.random.seed(0)
x1=np.random.randn(4,5)
x1

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

In [103]:
x1[1,[2,3]]=x1[1,[2,3]][::-1]
x1

array([[ 1.76405235,  0.40015721,  2.2408932 ,  0.97873798,  1.86755799],
       [-0.97727788,  0.95008842, -0.10321885, -0.15135721,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.12167502,  0.76103773,  0.44386323],
       [ 0.33367433,  1.49407907,  0.3130677 , -0.20515826, -0.85409574]])

In [106]:
x33=x1[:,[2]]
x1[:,[2]]=x1[:,[3]]
x1[:,[3]]=x33
x1

array([[ 1.76405235,  0.40015721,  2.2408932 ,  0.97873798,  1.86755799],
       [-0.97727788,  0.95008842, -0.10321885, -0.15135721,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.12167502,  0.76103773,  0.44386323],
       [ 0.33367433,  1.49407907,  0.3130677 , -0.20515826, -0.85409574]])

**Question 2**: 

create an array with the same shape as array x2, and fill it with the values of array x2 subtracetd by the mean of its values and divided to its standard deviation.


In [108]:
x2=np.array([[1,4,3,2,3,0],[23,59,0,-12,4,0]])


In [110]:
x2=(x2-np.mean(x2))/np.std(x2)
x2

array([[-0.36193893, -0.18820824, -0.24611847, -0.3040287 , -0.24611847,
        -0.41984916],
       [ 0.91208611,  2.99685436, -0.41984916, -1.11477191, -0.18820824,
        -0.41984916]])

## 2.5 Reshape Array

In [49]:
arr4.shape

(5, 6)

In [53]:
arr4=arr4.reshape((6,5))
arr4.shape


(6, 5)

In [54]:
arr4.transpose()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## 2.6 Input and Output Variables

In [56]:
#save arr4 in "array4"
np.save("array4",arr4)
arr4=67
arr4

67

In [58]:
#load
arr4=np.load('array4.npy')
arr4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
np.linalg.inv([[2,4],[5,7]])

array([[-1.16666667,  0.66666667],
       [ 0.83333333, -0.33333333]])

**Question 3**:

load the q3 array from "q3.npy" and implement Dot product of its transposed array with the array x3.


In [111]:
x3=np.ones((3,4))

In [114]:
q3=np.load("q3.npy")
np.dot(x3,q3.transpose())

array([[-0.60541786, -1.70246361, -1.06754432],
       [-0.60541786, -1.70246361, -1.06754432],
       [-0.60541786, -1.70246361, -1.06754432]])

## 2.7 Inspecting Array


In [64]:
a=np.array([[100,3],[22,1000]])
a

array([[ 100,    3],
       [  22, 1000]])

In [65]:
print("a.shape: ",a.shape)


a.shape:  (2, 2)


In [69]:
print("len(a): ",len(arr4))
arr4

len(a):  6


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [70]:
print("a.size: ",a.size)


a.size:  4


In [71]:
print("a.dtype: ",a.dtype)


a.dtype:  int32


In [72]:
a=a.astype(np.string_)
a

array([[b'100', b'3'],
       [b'22', b'1000']], dtype='|S11')

## 2.8 Sorting


In [74]:
b=np.array([[1,200,20],[20,100,12]])
# sort b axis 0
b

array([[  1, 200,  20],
       [ 20, 100,  12]])

In [77]:
# sort b axis 1

print(np.sort(b))

[[  1  20 200]
 [ 12  20 100]]


In [76]:
# sort b axis 1 descending 

np.sort(b,axis=1)

array([[  1,  20, 200],
       [ 12,  20, 100]])

In [80]:
b3=np.array([[[1,200],[2,30]],[[20,100],[12,78]]])
b3.shape


(2, 2, 2)

In [83]:
np.sort(b3,axis=2)

array([[[  1, 200],
        [  2,  30]],

       [[ 20, 100],
        [ 12,  78]]])

## 2.9  Combining Arrays 

note: arrays should be in same dims.

In [90]:
c=np.array([1,4,2])
d=np.array([50,40,20])
np.concatenate((c,d),axis=0)
# np.append(c,d)



array([ 1,  4,  2, 50, 40, 20])

In [92]:
e=np.array([[1,4],[2,6]])
f=np.array([[50,40],[1000,2000]])
# np.concatenate e,f   axis=1 or 0
np.concatenate((e,f),axis=0)


array([[   1,    4],
       [   2,    6],
       [  50,   40],
       [1000, 2000]])

In [93]:
# np.vstack e,f
np.vstack((e,f))

array([[   1,    4],
       [   2,    6],
       [  50,   40],
       [1000, 2000]])

In [94]:
# np.hstack e,f
np.hstack((e,f))

array([[   1,    4,   50,   40],
       [   2,    6, 1000, 2000]])

concatenate axis=0 => np.vstack((e,f)) AND axis=1 => np.hstack((e,f))

**Question 4**: 

look in the items inside the array x4 and replace the values more than 10 with -100 value

In [116]:
x4=np.array([range(9,12),[13,8,0]])


In [118]:
# for
for i in range(x4.shape[0]):
    for j in range(x4.shape[1]):
        if x4[i,j]>10:
            x4[i,j]=-100
x4

array([[   9,   10, -100],
       [-100,    8,    0]])

In [119]:
# 1 line
x4[x4>10]=-100
x4

array([[   9,   10, -100],
       [-100,    8,    0]])

**Question 5 **:
 
 Delete the elements in the array x5 which are larger than 10 and smaller than 20.
 
 Hint: use np.where(condition)

In [121]:
x5=np.array([1,3,13,20,8,0,12,23,10,2,3])

In [122]:
list1=np.where((x5>10) & (x5<20))
list1

(array([2, 6], dtype=int64),)

In [124]:
np.delete(x5,list1)

array([ 1,  3, 20,  8,  0, 23, 10,  2,  3])

**Qestion 6 **:

load the q3 variable form "q3.npy" and create a same-shaped array with np.random.randn(x,y); Afterwards, combine these arrays in both vertical and horizontal direction in a sorted way (axis=0 or 1).

In [ ]:
np.random.seed(0)

**Question 7**:

create 3-dimentional (2,3,2) array with np.random.randn and sort it along its third axis.
