## Numpy Assignment

####   Import the numpy package under the name `np` 

In [65]:
import numpy as np

#### 1.  Create a vector with values ranging from 10 to 49 and then reverse it (★☆☆)

In [66]:
Z1=np.arange(10,50)[::-1]
Z1

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

####  2. Create a zeros vector of size 10 but the fifth value which is 1 

In [67]:
Z2 = np.zeros(10)
Z2[4] = 1
print(Z2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 3. Create a 3x3 matrix with values ranging from 0 to 8 

In [68]:
Z3 = np.arange(9).reshape(3,3)
print(Z3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 4. Find indices of non-zero elements from \[1,2,0,0,4,0\] 

In [69]:
X=np.array([1,2,0,0,4,0])
l=np.where(X!=0)
l

(array([0, 1, 4]),)

#### 5. Create a 2d array with 1 on the border and 0 inside 

In [70]:
Z5 = np.ones((10,10))
Z5[1:-1,1:-1] = 0 #or : Z[1:9,1:9] = 0
print(Z5)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 6. Create a 8x8 matrix and fill it with a checkerboard pattern (★)

In [71]:
Z6 = np.zeros((8,8))
Z6[1::2,::2] = 1
Z6[::2,1::2] = 1
print(Z6)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 7. Given a 1D array, negate all elements which are between 3 and 8, in place. 

In [72]:
Z7 = np.arange(11)
Z7[(Z7 > 3) & (Z7 <= 8)] *= -1
print(Z7)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


####  8. Create a 5x5 matrix with row values ranging from 4 to 0 

In [73]:
Z8 = np.zeros((5,5))
Z8[:]=np.arange(5)[::-1]
print(Z8)

[[4. 3. 2. 1. 0.]
 [4. 3. 2. 1. 0.]
 [4. 3. 2. 1. 0.]
 [4. 3. 2. 1. 0.]
 [4. 3. 2. 1. 0.]]


#### 9. Create random vector of size 10 and replace the maximum value by 0 

In [74]:
Z9=np.random.randn(10)
print(Z9)
Z9[Z9==np.max(Z9)]=0
Z9

[ 0.76103773  0.12167502  0.44386323  0.33367433  1.49407907 -0.20515826
  0.3130677  -0.85409574 -2.55298982  0.6536186 ]


array([ 0.76103773,  0.12167502,  0.44386323,  0.33367433,  0.        ,
       -0.20515826,  0.3130677 , -0.85409574, -2.55298982,  0.6536186 ])

#### 10 Create a random vector of size 10 and sort it in both ascending and descending way

In [75]:
Z10=np.random.randn(10)
Z10_ascending=np.sort(Z10)
Z10_descending=np.sort(Z10)[::-1]
print(Z10_ascending)
print(Z10_descending)

[-1.45436567 -0.74216502 -0.18718385  0.04575852  0.15494743  0.37816252
  0.8644362   1.46935877  1.53277921  2.26975462]
[ 2.26975462  1.53277921  1.46935877  0.8644362   0.37816252  0.15494743
  0.04575852 -0.18718385 -0.74216502 -1.45436567]


#### Qestion 6 :

#### load the q3 variable form "q3.npy" and create a same-shaped array with np.random.randn(x,y); Afterwards, combine these arrays in both vertical and horizontal direction in a sorted way (axis=0 or 1).

In [76]:
np.random.seed(0)
q3=np.load("q3.npy")
x6=np.random.randn(q3.shape[0],q3.shape[1])
print("q3:",q3)
print("\n")
print("X6:",x6)

q3: [[-0.93168824 -0.16892007 -0.10301861  0.59820906]
 [-0.49871331 -0.74482859  0.56573201 -1.02465373]
 [-0.47633474 -0.5145974   0.66564209 -0.74225427]]


X6: [[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]]


In [77]:
# np.vstack((q3,x6))
np.sort(np.vstack((q3,x6)),axis=0) 

array([[-0.93168824, -0.97727788, -0.10301861, -1.02465373],
       [-0.49871331, -0.74482859,  0.14404357, -0.74225427],
       [-0.47633474, -0.5145974 ,  0.56573201, -0.15135721],
       [-0.10321885, -0.16892007,  0.66564209,  0.59820906],
       [ 1.76405235,  0.40015721,  0.95008842,  1.45427351],
       [ 1.86755799,  0.4105985 ,  0.97873798,  2.2408932 ]])

In [78]:
# reverse :
np.sort(np.vstack((q3,x6)),axis=0)[::-1]

array([[ 1.86755799,  0.4105985 ,  0.97873798,  2.2408932 ],
       [ 1.76405235,  0.40015721,  0.95008842,  1.45427351],
       [-0.10321885, -0.16892007,  0.66564209,  0.59820906],
       [-0.47633474, -0.5145974 ,  0.56573201, -0.15135721],
       [-0.49871331, -0.74482859,  0.14404357, -0.74225427],
       [-0.93168824, -0.97727788, -0.10301861, -1.02465373]])

In [79]:
np.sort(np.vstack((q3,x6)),axis=1) 

array([[-0.93168824, -0.16892007, -0.10301861,  0.59820906],
       [-1.02465373, -0.74482859, -0.49871331,  0.56573201],
       [-0.74225427, -0.5145974 , -0.47633474,  0.66564209],
       [ 0.40015721,  0.97873798,  1.76405235,  2.2408932 ],
       [-0.97727788, -0.15135721,  0.95008842,  1.86755799],
       [-0.10321885,  0.14404357,  0.4105985 ,  1.45427351]])

In [80]:
# reverse : 
np.sort(np.vstack((q3,x6)),axis=1)[:,::-1]

array([[ 0.59820906, -0.10301861, -0.16892007, -0.93168824],
       [ 0.56573201, -0.49871331, -0.74482859, -1.02465373],
       [ 0.66564209, -0.47633474, -0.5145974 , -0.74225427],
       [ 2.2408932 ,  1.76405235,  0.97873798,  0.40015721],
       [ 1.86755799,  0.95008842, -0.15135721, -0.97727788],
       [ 1.45427351,  0.4105985 ,  0.14404357, -0.10321885]])

In [81]:
# np.hstack((q3,x6)):
np.sort(np.hstack((q3,x6)),axis=0)
np.sort(np.hstack((q3,x6)),axis=0)[::-1]
np.sort(np.hstack((q3,x6)),axis=1) 
np.sort(np.hstack((q3,x6)),axis=1)[:,::-1]

array([[ 2.2408932 ,  1.76405235,  0.97873798,  0.59820906,  0.40015721,
        -0.10301861, -0.16892007, -0.93168824],
       [ 1.86755799,  0.95008842,  0.56573201, -0.15135721, -0.49871331,
        -0.74482859, -0.97727788, -1.02465373],
       [ 1.45427351,  0.66564209,  0.4105985 ,  0.14404357, -0.10321885,
        -0.47633474, -0.5145974 , -0.74225427]])

**Question 7**:

#### create 3-dimentional (2,3,2) array with np.random.randn and sort it along its third axis.

In [82]:
np.random.seed(0)
np.sort(np.random.randn(2,3,2),axis=2)

array([[[ 0.40015721,  1.76405235],
        [ 0.97873798,  2.2408932 ],
        [-0.97727788,  1.86755799]],

       [[-0.15135721,  0.95008842],
        [-0.10321885,  0.4105985 ],
        [ 0.14404357,  1.45427351]]])